services:
  db:
    image: mysql:latest
    env_file:
      - .env
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - /opt/jenkins_agent/workspace/${JOB_NAME}/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS} 
    ports:
      - "3306:3306"

  app:
    build: ./
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    env_file:
      - .env
    ports:
      - "5000:3000"
    depends_on: 
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge

