"""image_url size change

Revision ID: f03e0be62d07
Revises: 9a29addb57e7
Create Date: 2025-09-02 16:36:38.781793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f03e0be62d07'
down_revision = '9a29addb57e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=34),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=34),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
    op.execute("""
INSERT INTO `products` VALUES (1,'HP Envy 10',140000,'/images/hp.jpg'),(2,'Mac Book Pro',170000,'/images/apple.jpg'),(3,'Surface Pro',120000,'/images/surface.jpg')
""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=34),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=34),
               existing_nullable=True)

    # ### end Alembic commands ###
